### ISSUE TITLE
Typescript: undefined is not a function

### ISSUE THREAD

**Issue by elsom25** [mgechev/angular-aop#13] opened 2015-02-14 02:24 UTC
I've been trying to integrate aop for logging, and followed both the `README` and a [post you've made](https://groups.google.com/d/msg/angular/5dv-LjNRgDc/mz6MW7oySR0J), with no luck.

My typescript:

```typescript
/// <reference path="/typings/angularjs/angular.d.ts" />

interface Window { TEST : any; }

module MyApp {
  "use strict";

  export function boot(
    $log : ng.ILogService
  ) {
    $log.info("starting");
  }

  angular
    .module("my_app", [
      "uuid4",
      "ngTouch",
      "AngularAOP"
    ])
    .factory("log_aspect", [() => {
      return (data : any) => {
        console.log("==== HELLO ====");
        console.log(data);
      };
    }])
    .factory("DummyService", [() => {
      return {
        foo: () => { console.log("---- foo ----"); },
        bar: (a : any, b : any) => {
          console.log("---- bar ----", a, b);
          return a * b;
        }
      };
    }])
    .controller("BusController", [
      "DummyService",
      (DummyService : any) => {
        DummyService.foo();
        DummyService.bar(2, 3.14);
      }
    ])
    .config( ($provide : any, executeProvider : any) => {
      executeProvider.annotate($provide, {
        DummyService: [{
          jointPoint: "after",
          advice: "log_aspect"
        }]
      });
    })
    .run([
      "$log",
      window.TEST ? () => {} : boot
    ]);
}
```

and compiled js:

```js
var MyApp;
(function (MyApp) {
    "use strict";
    function boot($log) {
        $log.info("starting");
    }
    MyApp.boot = boot;
    angular.module("my_app", [
        "uuid4",
        "ngTouch",
        "AngularAOP"
    ]).factory("log_aspect", [function () {
        return function (data) {
            console.log("==== HELLO ====");
            console.log(data);
        };
    }]).factory("DummyService", [function () {
        return {
            foo: function () {
                console.log("---- foo ----");
            },
            bar: function (a, b) {
                console.log("---- bar ----", a, b);
                return a * b;
            }
        };
    }]).controller("BusController", [
        "DummyService",
        function (DummyService) {
            DummyService.foo();
            DummyService.bar(2, 3.14);
        }
    ]).config(function ($provide, executeProvider) {
        executeProvider.annotate($provide, {
            DummyService: [{
                jointPoint: "after",
                advice: "log_aspect"
            }]
        });
    }).run([
        "$log",
        window.TEST ? function () {
        } : boot
    ]);
})(MyApp || (MyApp = {}));
```

with console output:

```
 TypeError: undefined is not a function
    at Object.AspectBuilder._getFunctionAspect (main.js:11417)
    at Object.AspectBuilder._getObjectAspect (main.js:11434)
    at AspectCollection.AspectBuilder.buildAspect [as after] (main.js:11412)
    at main.js:11392
    at Object.invoke (main.js:3944)
    at Object.origProvider.$get (main.js:3896)
    at Object.invoke (main.js:3944)
    at main.js:3974
    at getService (main.js:3930)
    at Object.invoke (main.js:3942)
```

If there's any help you can provide it would be greatly appreciated! Really want to integrate this~

---
2015-02-14: Edited to port full typescript and compiled js

**Comment by mgechev** [comment] 2015-02-14 07:19
In what browser did you have the issue?

I wasn't able to [reproduce it in Chrome 40](http://plnkr.co/edit/6jQAnyOUPXfXVuwFDehl?p=preview).

**Comment by elsom25** [comment] 2015-02-14 17:08
Was Chrome 40.0.2214.111. But given it's working on plnkr, I guess it must be something else with my project environment.

**Comment by elsom25** [comment] 2015-02-14 17:21
Okay, ported proper typescript generated code [over to plnkr](http://plnkr.co/edit/Ej4yKx?p=preview), and the error is generating. My guess is it's something to do with typescripts anonymous wrapping.

**Comment by mgechev** [comment] 2015-02-14 20:11
There are dependencies which do not exist:

```javascript
// ...
angular.module("my_app", [
    "uuid4",
    "ngTouch",
    "AngularAOP"
]).factory("log_aspect", [function () {
// ...
```

Remove `ngTouch` and `uuid4` or add scripts, referencing to their definition, and it should work.

**Comment by elsom25** [comment] 2015-02-15 01:33
Okay, it works in plnkr, but not locally, so I played around a bit. If locally, I disable our single file merging, and load AOP separately it works, however, if I load it all in one file, I get the error in my original post when I include:

```js
.config(function($provide, executeProvider) {
  executeProvider.annotate($provide, {
      DummyService: [ {
          jointPoint: "after",
          advice: "LogAspect"
      } ]
  })
```

Not sure yet why merging into one file leads to this error, but its a start.

**Comment by mgechev** [comment] 2015-02-15 15:24
Are you sure you concatenate all script files in the appropriate order?

**Comment by elsom25** [comment] 2015-02-17 03:52
Yep! The order in the minified file was near identical to the exploded version (only difference was a completely external dependency used to be first, and with angular and angular-aop exploded out, is now 3rd, so should have no effect).

That said, I'm running into a problem with aop not applying to my non-dummy services. It's an angular service (v.s. factory as above, though that should have no effect) named in lowercase, `api`, and it seems no method calls attached to this service invoke my aop logger. No errors generated or anything, just nothing happening.

**Comment by mgechev** [comment] 2015-02-17 08:15
We can close this issue.

Please [mail me](http://blog.mgechev.com/about/) with details (code snippets) of the AngularAOP code you can't make work.

**Closed by mgechev** 2015-02-17 08:15 UTC

**Comment by elsom25** [comment] 2015-02-17 16:28
I would say this particular issue is still open given minification leads to this error, but that's your call. As for some services not working, it seems aop doesn't play nicely with typescript classes setup as services.

For reference, a class get's generated as:

```js
var DummyService = (function () {
        function DummyService() {
        }
        DummyService.prototype.foo = function () {
            console.log("---- DummyService::foo ----");
        };
        DummyService.prototype.bar = function (a, b) {
            console.log("---- DummyService::bar ----");
            return a * b;
        };
        DummyService.prototype.baz = function (a, b, c) {
            console.log("---- DummyService::baz ----");
            return c(a * b);
        };
        return DummyService;
    })();
```

**Comment by mgechev** [comment] 2015-02-17 17:49
It is developers' responsibility to manage the order the dependencies of his project are concatenated. The purpose of AngularAOP is only to provide a way to deal with cross-cutting concerns inside your AngularJS project. Even minification tools like uglifyjs delegate the concatenation order to the developer since the dependency resolution is a hard problem, especially in weakly typed languages like JavaScript. This is the reason I closed the issue, since it is not relevant to the framework.

---

In your code snippet you don't define `DummyService` properly. Take a look at [AngularJS' documentation](https://docs.angularjs.org/guide/services).

Here is how it should be:

```javascript
var DemoApp = angular.module('DemoApp', ['AngularAOP']);

DemoApp.controller('DummyController', function (DummyService) {
  DummyService.foo();  
});

DemoApp.service("DummyService", ["$log", function DummyService($log) {
  this.foo = function () {
      $log.info("---- DummyService::foo ----");
  };
  this.bar = function (a, b) {
      $log.info("---- DummyService::bar ----");
      return a * b;
  };
  this.baz = function (a, b, c) {
      $log.info("---- DummyService::baz ----");
      return c(a * b);
  };
}]);

DemoApp.factory('Logger', function () {
  return function (args) {
    console.log('Dummy logger');
  };
});

DemoApp.config(function ($provide, executeProvider) {
  executeProvider.annotate($provide, {
    DummyService: [{
      jointPoint: 'after',
      advice: 'Logger'
    }]
  });
});
```

```html
<!DOCTYPE HTML>
<html lang="en" data-ng-app="DemoApp">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body data-ng-controller="DummyController">
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.3/angular.min.js"></script>
    <script src="https://rawgithub.com/mgechev/angular-aop/master/build/angular-aop.min.js"></script>
    <script src="demo.js"></script>
    Open console to see the action!
</body>
</html>
```

[And working plunker.](http://plnkr.co/edit/di2lzFIu8p5Ta8GObaYa?p=preview)

**Comment by elsom25** [comment] 2015-02-17 17:53
Okay, so my service does work when defined as I have done, but yes, it is a mild divergence from Angular docs. 

Maybe make a note on the README that typescript classes will not play with AOP? (or something more generic about the service requiring strict conformance to the angular docs?)

I'll see how much effort would be involved in porting my necessary code away from classes and services into simple factories. Thanks.

**Comment by mgechev** [comment] 2015-02-17 17:54
It is not necessary to use `factory` instead of `service`, but you should use `service` the right way. `service` accepts a function, which is later invoked with `new`. The result is being cached internally in the `provider`.

**Comment by elsom25** [comment] 2015-02-17 18:15
Unfortunately because of how typescript generates classes, we don't have the ability to do services the right way. We were using them canonically

```js
.service("api", ["$log", APICaller]);
```

but when `APICaller` is a typescript class, it seems to be ignored by aop. I attempted a few different dummy samples that were structured similarly to the output of typescript, which is what led to the code above. Fortunately, it's not too difficult to swap out the class construct for a module with an initialize function, which plays nicely.

**Comment by mgechev** [comment] 2015-02-17 19:17
Ok, thanks for the quick feedback! Tomorrow, I will try to reproduce this issue with typescript and resolve it.

**Comment by mgechev** [comment] 2015-02-18 03:56
AngularAOP didn't add wrappers to methods defined in the prototype.

The newest content in the master branch has a `deep` property, which indicates whether such wrappers should be added. Here is demo:

```javascript
var DemoApp = angular.module('DemoApp', ['AngularAOP']);

DemoApp.controller('DummyController', function (DummyService) {
  DummyService.foo();
});

interface ILogger {
  info: Function;
}

class DummyService {
  log: ILogger;
  constructor($log) {
    this.log = $log;
  }
  foo() {
    this.log.info("---- DummyService::foo ----");
  }
  bar(a: number, b: number) {
    this.log.info("---- DummyService::bar ----");
    return a * b;
  }
  baz(a: number, b: number, c: Function) {
    this.log.info("---- DummyService::baz ----");
    return c(a * b);
  }
}

DemoApp.service("DummyService", ["$log", DummyService]);

DemoApp.factory('Logger', function () {
  return function (args) {
    console.log('Dummy logger');
  };
});

DemoApp.config(function ($provide, executeProvider) {
  executeProvider.annotate($provide, {
    DummyService: [{
      jointPoint: 'after',
      advice: 'Logger',
      deep: true
    }]
  });
});
```

**Comment by elsom25** [comment] 2015-02-18 07:51
beautiful! Thanks so much for extending~

**Comment by elsom25** [comment] 2015-02-18 15:53
Okay, maybe I'm missing something, but I can't seem to get your example working (no errors, but no logging either).

```ts
  class MyDummyService {
    constructor(
      private log : ng.ILogService
    ) { }

    public foo() {
      this.log.info("---- DummyService::foo ----");
    }
    public bar(a: number, b: number) {
      this.log.info("---- DummyService::bar ----");
      return a * b;
    }
    public baz(a: number, b: number, c: Function) {
      this.log.info("---- DummyService::baz ----");
      return c(a * b);
    }
  }

  angular
    .module("DemoApp", [
      "AngularAOP"
    ])
    .service("DummyService", ["$log", MyDummyService])
    .controller("DemoController", ["DummyService", (dummyService : MyDummyService) => {
      dummyService.foo();
      dummyService.bar(2, 3);
    }])
    .config( ($provide : any, executeProvider : any) => {
      executeProvider.annotate($provide, {
        DummyService: [{
          jointPoint: "after",
          advice: "Aspects.Logger",
          deep: true
        }]
      });
    });
```

**Comment by mgechev** [comment] 2015-02-18 23:47
If you are using AngularAOP via bower it will not work yet. Tonight I will create a new tag.

**Comment by mgechev** [comment] 2015-02-19 01:02
@elsom25 [here is demo](http://plnkr.co/edit/UGBjkRyr0B31m7v7nsXF?p=preview).

If you want to use it via bower you can:

``bash
bower install angular-aop#0.3.1
```

**Comment by elsom25** [comment] 2015-02-19 01:11
@mgechev thanks! Was running with #master but will be nice to swap back to versioned land. Thanks so much for the help, and for the quick fix!
